### ISSUE TITLE
native Go version

### ISSUE THREAD

**Issue by nikolaydubina** [laixintao/flameshow#52]
Is there big blockers for creating this in Go? Especially given it's first use-case was Go pprof.

**Comment by laixintao** [comment]
Haha, the big blocker is the TUI lib I use, textual, which is written in Python.

Textual(https://www.textualize.io/) is an awesome project, those guys put a lot of efforts on TUI, which makes this project `flameshow` possible. Actually I don't think any other language has the equivalent lib like textual.

But what issues do you got? consider this is only a cli not a lib that you need to refer in your code, so written any language should be ok I think? 

Or you got some issues installing it in some environment? Maybe I can package it into a binary without any dependency on ssytem? like iredis? (https://github.com/laixintao/iredis#download-binary)

**Comment by laixintao** [comment]
Going to close this issue if you have no issues about the installation.

**Comment by leesheen** [comment]
> Haha, the big blocker is the TUI lib I use, textual, which is written in Python.
> 
> Textual(https://www.textualize.io/) is an awesome project, those guys put a lot of efforts on TUI, which makes this project `flameshow` possible. Actually I don't think any other language has the equivalent lib like textual.
> 
> But what issues do you got? consider this is only a cli not a lib that you need to refer in your code, so written any language should be ok I think?
> 
> Or you got some issues installing it in some environment? Maybe I can package it into a binary without any dependency on ssytem? like iredis? (https://github.com/laixintao/iredis#download-binary)

Good idea! It's hard to describe the python version in many prod env.
