### ISSUE TITLE
Root nodes render syntax instead of color

### ISSUE THREAD

**Issue by mattrobenolt** [laixintao/flameshow#78]
Not sure how else to describe it, but here's the visual:

<img width="605" alt="image" src="https://github.com/user-attachments/assets/3549f031-5099-4cd5-9f36-0bba113f7fba">

It seems very specifically all of my root nodes get rendered with `[b red] [/b red]`, and this is in every single view.

<img width="677" alt="image" src="https://github.com/user-attachments/assets/0524875b-bdba-4c8d-b266-7fdd60b77348">

**Comment by laixintao** [comment]
Yeah seems like a bug. Let me take a look
